version: '3.4'
 
networks:
    myAppNetwork:       
 
services:
    blazor:
        container_name: Algobot
        image: ${DOCKER_REGISTRY-}algobot-worker
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            BinanceApi__ApiKey: ${BinanceApi__ApiKey}
            BinanceApi__SecretKey: ${BinanceApi__SecretKey}
            CoinMarketCap__ApiKey: ${CoinMarketCap__ApiKey}
            ApiKeyOptions__ApiKey: ${ApiKeyOptions__ApiKey}